apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
	name: prevent-privileged
spec:
	privileged: false
	seLinux:
		rule: RunAsAny
	supplementalGroups:
		rule: RunAsAny
	runAsUser:
		rule: RunAsAny
	fsGroup:
		rule: RunAsAny
	volumes:
	- '*'
